//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod chats;
pub mod contacts;
pub mod skills;
pub mod users;
pub mod users_learns_skills;
pub mod users_teaches_skills;
