//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::learns::Entity as Learns;
pub use super::skills::Entity as Skills;
pub use super::teaches::Entity as Teaches;
pub use super::users::Entity as Users;
