//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "skills")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::users_learns_skills::Entity")]
    UsersLearnsSkills,
    #[sea_orm(has_many = "super::users_teaches_skills::Entity")]
    UsersTeachesSkills,
}

impl Related<super::users_learns_skills::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UsersLearnsSkills.def()
    }
}

impl Related<super::users_teaches_skills::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UsersTeachesSkills.def()
    }
}
