//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub first_name: String,
    pub last_name: String,
    #[sea_orm(unique)]
    pub email: String,
    pub discord_id: Option<String>,
    pub provider: String,
    pub token_version: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub profile_pic: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::chats::Entity")]
    Chats,
    #[sea_orm(has_many = "super::users_learns_skills::Entity")]
    UsersLearnsSkills,
    #[sea_orm(has_many = "super::users_teaches_skills::Entity")]
    UsersTeachesSkills,
}

impl Related<super::chats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Chats.def()
    }
}

impl Related<super::users_learns_skills::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UsersLearnsSkills.def()
    }
}

impl Related<super::users_teaches_skills::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UsersTeachesSkills.def()
    }
}
